package com.school.system.domain;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_teacherid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer courseTeacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_weekday
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer courseWeekday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_time
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer courseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_place
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String coursePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_type
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer courseType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_teacherid
     *
     * @return the value of course.course_teacherid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getCourseTeacherid() {
        return courseTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_teacherid
     *
     * @param courseTeacherid the value for course.course_teacherid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setCourseTeacherid(Integer courseTeacherid) {
        this.courseTeacherid = courseTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_weekday
     *
     * @return the value of course.course_weekday
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getCourseWeekday() {
        return courseWeekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_weekday
     *
     * @param courseWeekday the value for course.course_weekday
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setCourseWeekday(Integer courseWeekday) {
        this.courseWeekday = courseWeekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_time
     *
     * @return the value of course.course_time
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_time
     *
     * @param courseTime the value for course.course_time
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setCourseTime(Integer courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_place
     *
     * @return the value of course.course_place
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getCoursePlace() {
        return coursePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_place
     *
     * @param coursePlace the value for course.course_place
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setCoursePlace(String coursePlace) {
        this.coursePlace = coursePlace == null ? null : coursePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_type
     *
     * @return the value of course.course_type
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_type
     *
     * @param courseType the value for course.course_type
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setCourseType(Integer courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", courseName=").append(courseName);
        sb.append(", courseTeacherid=").append(courseTeacherid);
        sb.append(", courseWeekday=").append(courseWeekday);
        sb.append(", courseTime=").append(courseTime);
        sb.append(", coursePlace=").append(coursePlace);
        sb.append(", courseType=").append(courseType);
        sb.append("]");
        return sb.toString();
    }
}