package com.school.system.domain;

public class Evaluate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_teacherid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer evaluateTeacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_studentid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer evaluateStudentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_score
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String evaluateScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_comment
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String evaluateComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.id
     *
     * @return the value of evaluate.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.id
     *
     * @param id the value for evaluate.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_teacherid
     *
     * @return the value of evaluate.evaluate_teacherid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getEvaluateTeacherid() {
        return evaluateTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_teacherid
     *
     * @param evaluateTeacherid the value for evaluate.evaluate_teacherid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setEvaluateTeacherid(Integer evaluateTeacherid) {
        this.evaluateTeacherid = evaluateTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_studentid
     *
     * @return the value of evaluate.evaluate_studentid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getEvaluateStudentid() {
        return evaluateStudentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_studentid
     *
     * @param evaluateStudentid the value for evaluate.evaluate_studentid
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setEvaluateStudentid(Integer evaluateStudentid) {
        this.evaluateStudentid = evaluateStudentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_score
     *
     * @return the value of evaluate.evaluate_score
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getEvaluateScore() {
        return evaluateScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_score
     *
     * @param evaluateScore the value for evaluate.evaluate_score
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setEvaluateScore(String evaluateScore) {
        this.evaluateScore = evaluateScore == null ? null : evaluateScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_comment
     *
     * @return the value of evaluate.evaluate_comment
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getEvaluateComment() {
        return evaluateComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_comment
     *
     * @param evaluateComment the value for evaluate.evaluate_comment
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setEvaluateComment(String evaluateComment) {
        this.evaluateComment = evaluateComment == null ? null : evaluateComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", evaluateTeacherid=").append(evaluateTeacherid);
        sb.append(", evaluateStudentid=").append(evaluateStudentid);
        sb.append(", evaluateScore=").append(evaluateScore);
        sb.append(", evaluateComment=").append(evaluateComment);
        sb.append("]");
        return sb.toString();
    }
}