package com.school.system.domain;

public class MajorCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_course.id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_course.mc_major_id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    private Integer mcMajorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_course.mc_course_id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    private Integer mcCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_course.id
     *
     * @return the value of major_course.id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_course.id
     *
     * @param id the value for major_course.id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_course.mc_major_id
     *
     * @return the value of major_course.mc_major_id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    public Integer getMcMajorId() {
        return mcMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_course.mc_major_id
     *
     * @param mcMajorId the value for major_course.mc_major_id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    public void setMcMajorId(Integer mcMajorId) {
        this.mcMajorId = mcMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_course.mc_course_id
     *
     * @return the value of major_course.mc_course_id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    public Integer getMcCourseId() {
        return mcCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_course.mc_course_id
     *
     * @param mcCourseId the value for major_course.mc_course_id
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    public void setMcCourseId(Integer mcCourseId) {
        this.mcCourseId = mcCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mcMajorId=").append(mcMajorId);
        sb.append(", mcCourseId=").append(mcCourseId);
        sb.append("]");
        return sb.toString();
    }
}