package com.school.system.domain;

import java.util.Date;

public class Paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_file
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    private String paperFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_student_id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    private Integer paperStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_create_time
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    private Date paperCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_state
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    private Integer paperState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.paper_course_id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    private Integer paperCourseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.id
     *
     * @return the value of paper.id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.id
     *
     * @param id the value for paper.id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_file
     *
     * @return the value of paper.paper_file
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public String getPaperFile() {
        return paperFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_file
     *
     * @param paperFile the value for paper.paper_file
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setPaperFile(String paperFile) {
        this.paperFile = paperFile == null ? null : paperFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_student_id
     *
     * @return the value of paper.paper_student_id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Integer getPaperStudentId() {
        return paperStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_student_id
     *
     * @param paperStudentId the value for paper.paper_student_id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setPaperStudentId(Integer paperStudentId) {
        this.paperStudentId = paperStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_create_time
     *
     * @return the value of paper.paper_create_time
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Date getPaperCreateTime() {
        return paperCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_create_time
     *
     * @param paperCreateTime the value for paper.paper_create_time
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setPaperCreateTime(Date paperCreateTime) {
        this.paperCreateTime = paperCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_state
     *
     * @return the value of paper.paper_state
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Integer getPaperState() {
        return paperState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_state
     *
     * @param paperState the value for paper.paper_state
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setPaperState(Integer paperState) {
        this.paperState = paperState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.paper_course_id
     *
     * @return the value of paper.paper_course_id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Integer getPaperCourseId() {
        return paperCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.paper_course_id
     *
     * @param paperCourseId the value for paper.paper_course_id
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setPaperCourseId(Integer paperCourseId) {
        this.paperCourseId = paperCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", paperFile=").append(paperFile);
        sb.append(", paperStudentId=").append(paperStudentId);
        sb.append(", paperCreateTime=").append(paperCreateTime);
        sb.append(", paperState=").append(paperState);
        sb.append(", paperCourseId=").append(paperCourseId);
        sb.append("]");
        return sb.toString();
    }
}