package com.school.system.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public PaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPaperFileIsNull() {
            addCriterion("paper_file is null");
            return (Criteria) this;
        }

        public Criteria andPaperFileIsNotNull() {
            addCriterion("paper_file is not null");
            return (Criteria) this;
        }

        public Criteria andPaperFileEqualTo(String value) {
            addCriterion("paper_file =", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileNotEqualTo(String value) {
            addCriterion("paper_file <>", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileGreaterThan(String value) {
            addCriterion("paper_file >", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileGreaterThanOrEqualTo(String value) {
            addCriterion("paper_file >=", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileLessThan(String value) {
            addCriterion("paper_file <", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileLessThanOrEqualTo(String value) {
            addCriterion("paper_file <=", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileLike(String value) {
            addCriterion("paper_file like", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileNotLike(String value) {
            addCriterion("paper_file not like", value, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileIn(List<String> values) {
            addCriterion("paper_file in", values, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileNotIn(List<String> values) {
            addCriterion("paper_file not in", values, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileBetween(String value1, String value2) {
            addCriterion("paper_file between", value1, value2, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperFileNotBetween(String value1, String value2) {
            addCriterion("paper_file not between", value1, value2, "paperFile");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdIsNull() {
            addCriterion("paper_student_id is null");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdIsNotNull() {
            addCriterion("paper_student_id is not null");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdEqualTo(Integer value) {
            addCriterion("paper_student_id =", value, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdNotEqualTo(Integer value) {
            addCriterion("paper_student_id <>", value, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdGreaterThan(Integer value) {
            addCriterion("paper_student_id >", value, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("paper_student_id >=", value, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdLessThan(Integer value) {
            addCriterion("paper_student_id <", value, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("paper_student_id <=", value, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdIn(List<Integer> values) {
            addCriterion("paper_student_id in", values, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdNotIn(List<Integer> values) {
            addCriterion("paper_student_id not in", values, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("paper_student_id between", value1, value2, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("paper_student_id not between", value1, value2, "paperStudentId");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeIsNull() {
            addCriterion("paper_create_time is null");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeIsNotNull() {
            addCriterion("paper_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeEqualTo(Date value) {
            addCriterion("paper_create_time =", value, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeNotEqualTo(Date value) {
            addCriterion("paper_create_time <>", value, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeGreaterThan(Date value) {
            addCriterion("paper_create_time >", value, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("paper_create_time >=", value, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeLessThan(Date value) {
            addCriterion("paper_create_time <", value, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("paper_create_time <=", value, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeIn(List<Date> values) {
            addCriterion("paper_create_time in", values, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeNotIn(List<Date> values) {
            addCriterion("paper_create_time not in", values, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeBetween(Date value1, Date value2) {
            addCriterion("paper_create_time between", value1, value2, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("paper_create_time not between", value1, value2, "paperCreateTime");
            return (Criteria) this;
        }

        public Criteria andPaperStateIsNull() {
            addCriterion("paper_state is null");
            return (Criteria) this;
        }

        public Criteria andPaperStateIsNotNull() {
            addCriterion("paper_state is not null");
            return (Criteria) this;
        }

        public Criteria andPaperStateEqualTo(Integer value) {
            addCriterion("paper_state =", value, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateNotEqualTo(Integer value) {
            addCriterion("paper_state <>", value, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateGreaterThan(Integer value) {
            addCriterion("paper_state >", value, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("paper_state >=", value, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateLessThan(Integer value) {
            addCriterion("paper_state <", value, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateLessThanOrEqualTo(Integer value) {
            addCriterion("paper_state <=", value, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateIn(List<Integer> values) {
            addCriterion("paper_state in", values, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateNotIn(List<Integer> values) {
            addCriterion("paper_state not in", values, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateBetween(Integer value1, Integer value2) {
            addCriterion("paper_state between", value1, value2, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperStateNotBetween(Integer value1, Integer value2) {
            addCriterion("paper_state not between", value1, value2, "paperState");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdIsNull() {
            addCriterion("paper_course_id is null");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdIsNotNull() {
            addCriterion("paper_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdEqualTo(Integer value) {
            addCriterion("paper_course_id =", value, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdNotEqualTo(Integer value) {
            addCriterion("paper_course_id <>", value, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdGreaterThan(Integer value) {
            addCriterion("paper_course_id >", value, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("paper_course_id >=", value, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdLessThan(Integer value) {
            addCriterion("paper_course_id <", value, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("paper_course_id <=", value, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdIn(List<Integer> values) {
            addCriterion("paper_course_id in", values, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdNotIn(List<Integer> values) {
            addCriterion("paper_course_id not in", values, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("paper_course_id between", value1, value2, "paperCourseId");
            return (Criteria) this;
        }

        public Criteria andPaperCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("paper_course_id not between", value1, value2, "paperCourseId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 04 16:31:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table paper
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}