package com.school.system.domain;

import java.util.ArrayList;
import java.util.List;

public class ScoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public ScoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdIsNull() {
            addCriterion("score_student_id is null");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdIsNotNull() {
            addCriterion("score_student_id is not null");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdEqualTo(Integer value) {
            addCriterion("score_student_id =", value, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdNotEqualTo(Integer value) {
            addCriterion("score_student_id <>", value, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdGreaterThan(Integer value) {
            addCriterion("score_student_id >", value, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("score_student_id >=", value, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdLessThan(Integer value) {
            addCriterion("score_student_id <", value, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("score_student_id <=", value, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdIn(List<Integer> values) {
            addCriterion("score_student_id in", values, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdNotIn(List<Integer> values) {
            addCriterion("score_student_id not in", values, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("score_student_id between", value1, value2, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("score_student_id not between", value1, value2, "scoreStudentId");
            return (Criteria) this;
        }

        public Criteria andScoreScoreIsNull() {
            addCriterion("score_score is null");
            return (Criteria) this;
        }

        public Criteria andScoreScoreIsNotNull() {
            addCriterion("score_score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreScoreEqualTo(String value) {
            addCriterion("score_score =", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreNotEqualTo(String value) {
            addCriterion("score_score <>", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreGreaterThan(String value) {
            addCriterion("score_score >", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score_score >=", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreLessThan(String value) {
            addCriterion("score_score <", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreLessThanOrEqualTo(String value) {
            addCriterion("score_score <=", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreLike(String value) {
            addCriterion("score_score like", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreNotLike(String value) {
            addCriterion("score_score not like", value, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreIn(List<String> values) {
            addCriterion("score_score in", values, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreNotIn(List<String> values) {
            addCriterion("score_score not in", values, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreBetween(String value1, String value2) {
            addCriterion("score_score between", value1, value2, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreScoreNotBetween(String value1, String value2) {
            addCriterion("score_score not between", value1, value2, "scoreScore");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdIsNull() {
            addCriterion("score_course_id is null");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdIsNotNull() {
            addCriterion("score_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdEqualTo(Integer value) {
            addCriterion("score_course_id =", value, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdNotEqualTo(Integer value) {
            addCriterion("score_course_id <>", value, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdGreaterThan(Integer value) {
            addCriterion("score_course_id >", value, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("score_course_id >=", value, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdLessThan(Integer value) {
            addCriterion("score_course_id <", value, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("score_course_id <=", value, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdIn(List<Integer> values) {
            addCriterion("score_course_id in", values, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdNotIn(List<Integer> values) {
            addCriterion("score_course_id not in", values, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("score_course_id between", value1, value2, "scoreCourseId");
            return (Criteria) this;
        }

        public Criteria andScoreCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("score_course_id not between", value1, value2, "scoreCourseId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 04 16:31:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score
     *
     * @mbg.generated Thu Apr 04 16:31:56 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}