package com.school.system.domain;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_num
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_class_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer studentClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_major_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer studentMajorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_password
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String studentPassword;
    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_num
     *
     * @return the value of student.student_num
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_num
     *
     * @param studentNum the value for student.student_num
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_class_id
     *
     * @return the value of student.student_class_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getStudentClassId() {
        return studentClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_class_id
     *
     * @param studentClassId the value for student.student_class_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setStudentClassId(Integer studentClassId) {
        this.studentClassId = studentClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_major_id
     *
     * @return the value of student.student_major_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getStudentMajorId() {
        return studentMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_major_id
     *
     * @param studentMajorId the value for student.student_major_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setStudentMajorId(Integer studentMajorId) {
        this.studentMajorId = studentMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_password
     *
     * @return the value of student.student_password
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_password
     *
     * @param studentPassword the value for student.student_password
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentNum=").append(studentNum);
        sb.append(", studentName=").append(studentName);
        sb.append(", studentClassId=").append(studentClassId);
        sb.append(", studentMajorId=").append(studentMajorId);
        sb.append(", studentPassword=").append(studentPassword);
        sb.append("]");
        return sb.toString();
    }
}