package com.school.system.domain;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_num
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String teacherNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_major_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private Integer teacherMajorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_password
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    private String teacherPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_name
     *
     * @return the value of teacher.teacher_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_name
     *
     * @param teacherName the value for teacher.teacher_name
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_num
     *
     * @return the value of teacher.teacher_num
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getTeacherNum() {
        return teacherNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_num
     *
     * @param teacherNum the value for teacher.teacher_num
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setTeacherNum(String teacherNum) {
        this.teacherNum = teacherNum == null ? null : teacherNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_major_id
     *
     * @return the value of teacher.teacher_major_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public Integer getTeacherMajorId() {
        return teacherMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_major_id
     *
     * @param teacherMajorId the value for teacher.teacher_major_id
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setTeacherMajorId(Integer teacherMajorId) {
        this.teacherMajorId = teacherMajorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_password
     *
     * @return the value of teacher.teacher_password
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public String getTeacherPassword() {
        return teacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_password
     *
     * @param teacherPassword the value for teacher.teacher_password
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    public void setTeacherPassword(String teacherPassword) {
        this.teacherPassword = teacherPassword == null ? null : teacherPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", teacherName=").append(teacherName);
        sb.append(", teacherNum=").append(teacherNum);
        sb.append(", teacherMajorId=").append(teacherMajorId);
        sb.append(", teacherPassword=").append(teacherPassword);
        sb.append("]");
        return sb.toString();
    }
}