package com.school.system.dao;

import com.school.system.domain.Clazz;
import com.school.system.domain.ClazzExample;
import com.school.system.domain.dto.ClazzDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    long countByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int deleteByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
     List<Clazz> selectByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    Clazz selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByExample(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByPrimaryKey(Clazz record);

    List<ClazzDto> selectAllClazzDtos();
}