package com.school.system.dao;

import com.school.system.domain.CourseStudent;
import com.school.system.domain.CourseStudentExample;
import com.school.system.domain.dto.CourseDto;
import com.school.system.domain.dto.StudentFileDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    long countByExample(CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int deleteByExample(CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int insert(CourseStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int insertSelective(CourseStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    List<CourseStudent> selectByExample(CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    CourseStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseStudent record, @Param("example") CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByExample(@Param("record") CourseStudent record, @Param("example") CourseStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByPrimaryKeySelective(CourseStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_student
     *
     * @mbg.generated Tue Apr 02 15:48:47 CST 2019
     */
    int updateByPrimaryKey(CourseStudent record);

    List<CourseDto> selectCourseDtosByStudentId(Integer studentId);

    List<StudentFileDto> selectStudentDtosByCourseId(Integer courseId);
}