package com.school.system.dao;

import com.school.system.domain.MajorCourse;
import com.school.system.domain.MajorCourseExample;
import com.school.system.domain.dto.MajorCourseDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MajorCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    long countByExample(MajorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int deleteByExample(MajorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int insert(MajorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int insertSelective(MajorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    List<MajorCourse> selectByExample(MajorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    MajorCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") MajorCourse record, @Param("example") MajorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int updateByExample(@Param("record") MajorCourse record, @Param("example") MajorCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int updateByPrimaryKeySelective(MajorCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_course
     *
     * @mbg.generated Thu Apr 04 11:58:29 CST 2019
     */
    int updateByPrimaryKey(MajorCourse record);

    List<MajorCourseDto> selectMajorCourseDtosByMajor(Integer majorId);
}